apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  driver_working_dir: {{ .Values.config.driverWorkingDir | quote }}
  k8s_root_dir: {{ .Values.config.k8SRootDir | quote }}
  mount_count: {{ .Values.config.mountCount | quote }}
  oras_logging: {{ .Values.config.orasLogging | quote }}