apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "chart.fullname" . }}-csi.oras.land
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral